accounts/urls.py
from django.contrib import admin
from django.urls import path,re_path
from django.conf.urls import url
from . import views

app_name='accounts'

urlpatterns = [

    path('signup/',views.signup_view,name="signup"),
    path('login/',views.login_view,name="login"),
    path('logout/',views.logout_view,name="logout"),
    path('',views.list,name="good"),
    path('create/',views.create_data,name="create"),
    re_path('(?P<slug>[\w-]+)/$',views.article,name="detail"),
]

copo/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/',include('accounts.urls')),
    path('data/',include('data.urls')),
    path('',views.homepage,name="hey"),
]

data/urls.py
from django.contrib import admin
from django.urls import path,re_path
from django.conf.urls import url
from . import views

app_name='data'
urlpatterns = [
    path('',views.list,name="good"),
    path('getmarks/',views.marks,name="create"),
    path('students/',views.student,name="students"),
    path('courses/',views.course,name="courses"),
    path('tables/',views.tab,name="tab"),
]

templates/base.html
{% load static %}
<!DOCTYPE html>

<html>
    <head>
        <meta charset="utf-8">
        <title>COPO</title>
    </head>
    <body>
    <header class ="wrapper">
    <h1><a href ="{% url 'hey' %}">COPO</a></h1>

    <nav>
        <ul>
            {% if user.is_authenticated %}
            <li>
                <form class="logout-link" action="{%url 'accounts:logout'%}" method="post">
                 {% csrf_token %}
                    <button type="submit">logout</button>
                </form>
            </li>
            <li><a href="{% url 'data:create' %}">Enter_marks</a></li>
            <li><a href="{% url 'data:students' %}">Enter Student Data</a></li>
            <li><a href="{% url 'data:courses' %}">Enter Courses</a></li>
            {% else %}
            <li><a href="{% url 'accounts:login' %}">Login</a></li>
            <li><a href="{% url 'accounts:signup' %}">Signup</a></li>
            {% endif %}
        </ul>
    </nav>
    </header>
    <div class="wrapper">
    {% block content%}

    {% endblock %}
    </div>
    </body>
</html>